
services:
  # Database
  genassist_db:
    image: postgres:15
    container_name: genassist_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    #  - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge # Network to connect all services